# Generated by Django 3.2.8 on 2022-01-03 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('chain', models.IntegerField(choices=[(0, 'Harmony one'), (1, 'Avalanche')], default=0)),
                ('decimals', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TokenPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('datetime', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=16, max_digits=30)),
            ],
        ),
    ]
